send_sms:
  name: Send SMS
  description: Send a text message to a mobile phone.
  fields:
    address:
      name: Number
      description: The adress of the mobile phone to send the message to.
      required: true
      example: "0123456789"
      selector:
        text:
    content:
      name: Message
      description: The message to send.
      required: true
      example: "Hello from Home Assistant!"
      selector:
        text:
